# Generated by Django 6.0.1 on 2026-01-27 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('figures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_reversed', models.BooleanField(default=False)),
                ('mapped_traits', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField()),
                ('trait_scores_0_3', models.JSONField()),
                ('dimension_averages_0_10', models.JSONField()),
                ('heinlein_averages', models.JSONField()),
                ('overall', models.JSONField()),
                ('best_match_similarity', models.FloatField(blank=True, null=True)),
                ('best_match_figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='figures.historicalfigure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
