# Generated by Django 6.0.3 on 2026-03-15 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentsubmission_match_results'),
        ('figures', '0004_alter_figureingestionrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentsubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['user', '-created_at'], name='assessments_user_id_e3e751_idx'),
        ),
    ]
