"""
Django settings for personliness project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-1an5vte(8t@rz4r(4lm(w$_%h8n)6dde%d7!n!&a963m^4s!cs')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'assessments',
    'figures',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'personliness.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'personliness.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'personliness'),
        'USER': os.environ.get('POSTGRES_USER', 'personliness'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'personliness'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

FIXTURE_DIRS = [
    BASE_DIR / "fixtures",
]

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Cache settings (used for queue locking)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0'),
    }
}

# Celery settings
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')

# LLM provider profiles
LLM_CONFIGS = {
    'openai-o3': {
        'base_url': 'https://api.openai.com/v1',
        'api_key_env': 'LLM_OPENAI_API_KEY',
        'model': os.environ.get('LLM_OPENAI_MODEL', 'o3'),
        'is_reasoning': True,
    },
    'openai-gpt4': {
        'base_url': 'https://api.openai.com/v1',
        'api_key_env': 'LLM_OPENAI_API_KEY',
        'model': os.environ.get('LLM_OPENAI_GPT4_MODEL', 'gpt-4-turbo'),
        'is_reasoning': False,
    },
    'anthropic': {
        'base_url': 'https://api.anthropic.com/v1',
        'api_key_env': 'LLM_ANTHROPIC_API_KEY',
        'model': os.environ.get('LLM_ANTHROPIC_MODEL', 'claude-opus-4-6'),
        'is_reasoning': False,
        'extended_thinking': True,
        'thinking_budget_tokens': 8000,
    },
    'ollama': {
        'base_url': os.environ.get('LLM_OLLAMA_BASE_URL', 'http://ollama:11434/v1'),
        'api_key_env': None,
        'model': os.environ.get('LLM_OLLAMA_MODEL', 'llama3'),
        'is_reasoning': False,
    },
}

LLM_ACTIVE_CONFIG = os.environ.get('LLM_ACTIVE_CONFIG', 'openai-o3')

# Backwards compatibility: old flat vars form an implicit 'custom' profile
_legacy_base_url = os.environ.get('LLM_BASE_URL')
_legacy_api_key  = os.environ.get('LLM_API_KEY')
_legacy_model    = os.environ.get('LLM_MODEL')
if _legacy_base_url or _legacy_model:
    LLM_CONFIGS['custom'] = {
        'base_url': _legacy_base_url or 'https://api.openai.com/v1',
        'api_key_env': None,
        'api_key': _legacy_api_key or '',
        'model': _legacy_model or 'o3',
        'is_reasoning': None,  # auto-detect from model name
    }
    if not os.environ.get('LLM_ACTIVE_CONFIG'):
        LLM_ACTIVE_CONFIG = 'custom'

# LLM confidence refinement settings (global, not per-profile)
LLM_ENABLE_REFINEMENT = os.environ.get('LLM_ENABLE_REFINEMENT', 'True') == 'True'
LLM_MAX_REFINEMENT_PASSES = int(os.environ.get('LLM_MAX_REFINEMENT_PASSES', '2'))
LLM_MIN_CONFIDENCE_TARGET = os.environ.get('LLM_MIN_CONFIDENCE_TARGET', 'High')

INGESTION_CONCURRENCY = int(os.environ.get('INGESTION_CONCURRENCY', '3'))

# Celery beat schedule - periodic fallback for queue processing
CELERY_BEAT_SCHEDULE = {
    'process-ingestion-queue': {
        'task': 'figures.tasks.process_ingestion_queue',
        'schedule': 300.0,  # Every 5 minutes
    },
}