# Generated by Django 6.0.1 on 2026-03-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figureingestionrequest',
            name='thinking_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
