# Generated by Django 6.0.3 on 2026-03-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0002_figureingestionrequest_thinking_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfigure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='figures/'),
        ),
        migrations.AlterField(
            model_name='figureingestionrequest',
            name='biography_text',
            field=models.TextField(blank=True),
        ),
    ]
