# Generated by Django 6.0.3 on 2026-03-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0003_historicalfigure_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figureingestionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
